pacman -S --asdeps --needed --noconfirm python
pacman -S --asdeps --needed --noconfirm gn
pacman -S --asdeps --needed --noconfirm ninja
pacman -S --asdeps --needed --noconfirm clang
pacman -S --asdeps --needed --noconfirm lld
pacman -S --asdeps --needed --noconfirm gperf
pacman -S --asdeps --needed --noconfirm nodejs
pacman -S --asdeps --needed --noconfirm pipewire
pacman -S --asdeps --needed --noconfirm rust
pacman -S --asdeps --needed --noconfirm rust-bindgen
pacman -S --asdeps --needed --noconfirm qt5-base
pacman -S --asdeps --needed --noconfirm qt6-base
pacman -S --asdeps --needed --noconfirm java-runtime-headless
pacman -S --asdeps --needed --noconfirm git
pacman -S --asdeps --needed --noconfirm python-httplib2
pacman -S --asdeps --needed --noconfirm python-pyparsing
pacman -S --asdeps --needed --noconfirm python-six
pacman -S --asdeps --needed --noconfirm npm
pacman -S --asdeps --needed --noconfirm rsync
